# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- adf_publish
- releases/*

jobs:
- job: linux_azure
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: '$(rootPath)/change_link_one_git.py'
      arguments: $(rootPath) $(adfNameShort) st $(keyValut)
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'DL-PR'
      ScriptType: 'FilePath'
      ScriptPath: './pre_post_script.ps1'
      ScriptArguments: -armTemplate '$(rootPath)/one/ARMTemplateForFactory.json'  -ResourceGroupName '$(resourceGroup)' -DataFactoryName '$(adfNameFull)' -predeployment $True
      azurePowerShellVersion: 'LatestVersion'
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'DL-PR'
      ScriptType: 'FilePath'
      ScriptPath: './deploy.ps1'
      ScriptArguments: -ResourceGroupName '$(resourceGroup)' -TemplateFile '$(rootPath)/one/ARMTemplateForFactory.json' -TemplateParametersFile '$(rootPath)/one/ARMTemplateParametersForFactory.json'
      azurePowerShellVersion: 'LatestVersion'
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'DL-PR'
      ScriptType: 'FilePath'
      ScriptPath: './pre_post_script.ps1'
      ScriptArguments: -armTemplate '$(rootPath)/one/ARMTemplateForFactory.json'  -ResourceGroupName '$(resourceGroup)' -DataFactoryName '$(adfNameFull)' -predeployment $False
      azurePowerShellVersion: 'LatestVersion'

- job: linux_agent
  pool: nestle-cn
  steps:
  - script: 
      chmod u+x azcopy
    displayName: 'enable execute'

  - script:
      ./azcopy copy "https://nchnexdep004sta.blob.core.chinacloudapi.cn/workspace/scripts/$(scriptPath)?sv=2020-10-02&st=2022-06-14T03%3A17%3A23Z&se=2023-06-15T03%3A17%3A00Z&sr=c&sp=rl&sig=hu%2FMHVGYQnfbRzkO5QFrZper%2Fp0D8qhsc0K5astGNJc%3D" "./" --recursive=true
    displayName: 'copy script from explake to local'

  - script:
      git clone -b hive_script $(gitRepo)
    displayName: 'git repo clone'

  - script:
      cp -r ./$(scriptPath) ./$(repoName)
    displayName: 'copy script to repo'

  - script:
      chmod u+x git.sh
    displayName: 'enable git shell'

  - script:
      ./git.sh
    displayName: 'git submit'

  - script:
      ./azcopy copy "./$(scriptPath)/*" "https://nchnstdep004sta.blob.core.chinacloudapi.cn/workspace/scripts/$(scriptPath)?sv=2020-10-02&st=2022-06-23T02%3A59%3A15Z&se=2023-06-24T02%3A59%3A00Z&sr=c&sp=rwl&sig=qYabU7cRli2uMS3satkIN3muadQO5OZqdSF9MPxGOK0%3D" --recursive=true
    displayName: 'copy script to stglake'
